import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#bec6e0",
        "inverse-primary": "#bec6e0",
        "surface-container-high": "#dce9ff",
        "tertiary-container": "#001a42",
        "tertiary": "#000000",
        "on-secondary": "#ffffff",
        "on-background": "#0b1c30",
        "primary": "#000000",
        "on-primary-fixed-variant": "#3f465c",
        "on-primary": "#ffffff",
        "on-primary-container": "#7c839b",
        "surface-container-low": "#eff4ff",
        "tertiary-fixed": "#d8e2ff",
        "surface": "#f8f9ff",
        "outline": "#76777d",
        "surface-tint": "#565e74",
        "secondary-container": "#6cf8bb",
        "error": "#ba1a1a",
        "primary-container": "#131b2e",
        "on-primary-fixed": "#131b2e",
        "on-surface": "#0b1c30",
        "on-tertiary-fixed": "#001a42",
        "outline-variant": "#c6c6cd",
        "surface-container-highest": "#d3e4fe",
        "on-secondary-fixed": "#002113",
        "on-surface-variant": "#45464d",
        "background": "#f8f9ff",
        "secondary-fixed-dim": "#4edea3",
        "inverse-surface": "#213145",
        "on-tertiary-container": "#3980f4",
        "surface-dim": "#cbdbf5",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#6ffbbe",
        "inverse-on-surface": "#eaf1ff",
        "secondary": "#006c49",
        "tertiary-fixed-dim": "#adc6ff",
        "on-tertiary-fixed-variant": "#004395",
        "on-secondary-container": "#00714d",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#005236",
        "surface-container": "#e5eeff",
        "surface-bright": "#f8f9ff",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface-variant": "#d3e4fe",
        "primary-fixed": "#dae2fd",
        "error-container": "#ffdad6",
        "habit-blue": "#3B82F6",
        "habit-green": "#10B981",
        "habit-purple": "#8B5CF6",
        "habit-red": "#EF4444",
        "habit-orange": "#F59E0B",
        "habit-pink": "#EC4899",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      spacing: {
        "margin-mobile": "16px",
        "container-max": "1200px",
        "section-gap": "48px",
        "margin-desktop": "40px",
        "gutter": "24px",
        "base": "8px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "sans-serif"],
        display: ["var(--font-hanken-grotesk)", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "monospace"],
      },
    },
  },
  plugins: [],
};
export default config;
